server:
  port: 8080   #tomcat端口号
  servlet:
    path: /   #前端控制器拦截的请求路径
    context-path: /  #上下文路径，必须以/开头，访问时必须先写上下文路径
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver #数据库配置
      url: jdbc:mysql://127.0.0.1:3306/db_room?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  jackson:
    date-format: yyyy-MM-dd
  thymeleaf:
    encoding: utf-8
    suffix: .html
    cache: false
  resources:    #静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

pagehelper:
  helper-dialect: mysql #数据库方言
  offset-as-page-num: true
  support-methods-arguments: true  # 方法参数中包含pageNum,pageSize参数时，自动进行分页
  params: count=countSql
  reasonable: true   # 传递参数的时候如果pageNum>totalpage时，默认pageNum=totalpage

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  identity: mysql
  not-empty: true
  style: normal

mybatis:
  mapper-locations: classpath*:/com/mapper/*.xml